apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: whoami
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: TCP
        port: 1337
        targetPort: 1337
  healthcheck:
    enabled: true
    image: us.gcr.io/imaginaryctf/whoami-healthcheck:4c60207f15259fe961f4c3120a1af80c1a150cfdd6439f648f33e3eee523ba25
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            env:
              - name: OPENROUTER_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: apikeys
                    key: openrouter
  image: us.gcr.io/imaginaryctf/whoami-challenge:ef0d924b6f23849bf356985348f86d6103bb066c6b65fef42ee1f4e1b6adf7c9
