apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: tax-return
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: TCP
        targetPort: 80
  healthcheck:
    enabled: true
    image: us.gcr.io/imaginaryctf/tax-return-healthcheck:7a32559cd8e826c463c41e864e8c57281681c8009de0f1055972f0ce9a1f056d
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            env:
              - name: OPENROUTER_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: apikeys
                    key: openrouter
  image: us.gcr.io/imaginaryctf/tax-return-challenge:373ec5da51db03069a59aaccb3ec8e5d237fd9ac8639d365e831f36815312d05
